name: Deploy Static Site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip the app
        run: zip -r site.zip .

      - name: Deploy using Kudu ZIP API
        run: |
          curl -X POST \
          -H "Content-Type: application/zip" \
          --data-binary @site.zip \
          "https://$WEBAPP_NAME.scm.azurewebsites.net/api/zipdeploy" \
          -u "$DEPLOYMENT_USERNAME:$DEPLOYMENT_PASSWORD"
    env:
      WEBAPP_NAME: webapp-harshita-18807
      DEPLOYMENT_USERNAME: "${{ secrets.KUDU_USERNAME }}"
      DEPLOYMENT_PASSWORD: "${{ secrets.KUDU_PASSWORD }}"
